/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const control: string;
const label: string;
const icon: string;

export {
	control,
	label,
	icon
};

export default {
	control,
	label,
	icon
};
