name: Deploy to Firebase on Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Build app
        run: npm run build
        env:
          VITE_FOURSQUARE_API_KEY: ${{ secrets.VITE_FOURSQUARE_API_KEY }}
          VITE_OFFICE_LAT: ${{ secrets.VITE_OFFICE_LAT }}
          VITE_OFFICE_LNG: ${{ secrets.VITE_OFFICE_LNG }}

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: cogent-labs-lunch